server:
  port: 8080
  servlet:
    context-path: /server
  tomcat:
    accesslog:
      enabled: true
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

spring:
  application:
    name: springvue-server
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mapper/**/*.xml
  global-config:
    db-config:
      capital-mode: true